services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment: # Usa env direto ao invés de arquivo
      - MONGODB_URI=mongodb://mongodb:27017 # Note: usa 'mongodb' (nome do service), não 'localhost'
      - MONGODB_DATABASE=auctions
      - BATCH_INSERT_INTERVAL=7m
      - MAX_BATCH_SIZE=10
      - AUCTION_INTERVAL=10m
    depends_on:
      - mongodb
    networks:
      - localNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge
